# This is the regional configuration file required by the application to specify the VPCs and/or subnets it is supposed to track 
# along with configuration required to setup traffic mirroring in those VPCs and/or subnets . 
# The configuration file follows a naming convention of <REGION_NAME>.yaml e.g. us-east-1.yaml
---
# VPC related configuration. You can enter configuration related to multiple VPCs here
vpcs:
- vpcId: <INSERT_VALUE> # required e.g. vpc-1a2b3c4d
  filterId: <INSERT_VALUE> # required e.g. tmf-06d57ab5b80cc5dc7

  # Set this property to use an existing Traffic Mirror target for all sessions. If using this option
  # we recommend using a target of type 'network-load-balancer' because a network-load-balancer based target
  # does not have any limits on the number of sources that mirror to it. If you do not set this property then
  # you must define the target instance properties below
  targetId: <INSERT_VALUE> # e.g. tmt-06d57ab5b80cc5dc7

  # Set these properties to have the app create Traffic Mirror targets on-demand by launching EC2 instances
  # with the following configurations. If 'targetId' is defined than these properties are ignored. If 'targetId' is
  # not defined than these properties are required
  targetInstanceType: <INSERT_VALUE> # e.g. c5.xlarge
  targetInstanceAmi: <INSERT_VALUE> # e.g. ami-04b762b4289fba92b
  targetSecurityGroupIds: 
  - <INSERT_VALUE> # e.g. sg-09b8aa62ffe25a174
  - <INSERT_VALUE> # e.g. sg-09b8aa62ffe25a174
  targetSubnetId: <INSERT_VALUE> # e.g. subnet-123456 # If not specified a target in the same subnet as source would be created/used

# Subnet related configuration. You can enter configuration related to multiple subnets here
# NOTE: A subnet configuration takes priority over VPC configuration
subnets:
- subnetId: <INSERT_VALUE> # required e.g. subnet-ecf5d8b6

  targetId: <INSERT_VALUE>
  
  targetInstanceType: <INSERT_VALUE>
  targetInstanceAmi: <INSERT_VALUE>
  targetSecurityGroupIds:
  - <INSERT_VALUE>
  - <INSERT_VALUE>
  filterId: <INSERT_VALUE>
  targetSubnetId: <INSERT_VALUE>

# Tags related configuration. You can enter configuration related to multiple tags here
# NOTE: A tag configuration takes priority over subnet configuration. Also, this works only for tags created during instance launch
# Any modifications to tags later would not be processed.
tags:
- tagList: # At least one tag (pair of of {key, value}) is required
  - Key: <INSERT_VALUE> # e.g. TagKey
    Value: <INSERT_VALUE> # required e.g. TagValue
  - Key: <INSERT_VALUE>
    Value: <INSERT_VALUE>

  targetId: <INSERT_VALUE>

  targetInstanceType: <INSERT_VALUE>
  targetInstanceAmi: <INSERT_VALUE>
  targetSecurityGroupIds:
  - <INSERT_VALUE>
  - <INSERT_VALUE>
  filterId: <INSERT_VALUE>
  targetSubnetId: <INSERT_VALUE>
